// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEJ6dLvXnKBIEDubPB_aPSIJbPadbiB0Y',
    appId: '1:989752138733:web:afb765dfb87fff0ccae5e4',
    messagingSenderId: '989752138733',
    projectId: 'chat3-b92d9',
    authDomain: 'chat3-b92d9.firebaseapp.com',
    storageBucket: 'chat3-b92d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAclWULR2hJXFnTyUfIvFYQOlH54-tCW84',
    appId: '1:989752138733:android:80458dc5d9a0e7eacae5e4',
    messagingSenderId: '989752138733',
    projectId: 'chat3-b92d9',
    storageBucket: 'chat3-b92d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAdpIY5VZlCB-0-dHdTRfi8tdpXQL333M',
    appId: '1:989752138733:ios:0665ea38a65a73d8cae5e4',
    messagingSenderId: '989752138733',
    projectId: 'chat3-b92d9',
    storageBucket: 'chat3-b92d9.appspot.com',
    iosBundleId: 'com.example.chat3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAdpIY5VZlCB-0-dHdTRfi8tdpXQL333M',
    appId: '1:989752138733:ios:5b842b3391279acbcae5e4',
    messagingSenderId: '989752138733',
    projectId: 'chat3-b92d9',
    storageBucket: 'chat3-b92d9.appspot.com',
    iosBundleId: 'com.example.chat3.RunnerTests',
  );
}
